const fs = require('fs');
const path = require('path');

// Read version from package.json
const packageJson = JSON.parse(fs.readFileSync(path.join(__dirname, '../package.json'), 'utf8'));
const version = packageJson.version;

// Path to version.ts file
const versionPath = path.join(__dirname, '../src/version.ts');

// Generate version file content
const versionContent = `// This file is auto-generated by scripts/inject-version.js
// DO NOT EDIT MANUALLY
export const VERSION = '${version}';
`;

// Write the version file
fs.writeFileSync(versionPath, versionContent);

console.log(`✓ Generated version.ts with version ${version}`);